// THIS IS FOR CREATE EVENT & BLOG

export const CLEAR_ALERT_MESSAGE = 'CLEAR_ALERT_MESSAGE';
export const ON_CREATING = 'ON_CREATING';
export const CREATED_FAIL = 'CREATED_FAIL';
export const CREATED_EVENT_SUCCESS = 'CREATED_EVENT_SUCCESS';

export const ON_POSTING_BLOG = 'ON_POSTING_BLOG';
export const POSTED_BLOG_SUCCESS = 'POSTED_BLOG_SUCCESS';

// THIS IS FOR AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const ON_AUTH = 'ON_AUTH';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

// THIS IS FOR PROFILE PAGE
export const ON_FETCHING_MY_BLOGS = 'ON_FETCHING_MY_BLOGS';
export const FETCH_MY_BLOGS_SUCCESS = 'FETCH_MY_BLOGS_SUCCESS';
export const DELETE_MY_BLOG_SUCCESS = 'DELETE_MY_BLOG_SUCCESS';

export const ON_FETCHING_RSVP_LIST = 'ON_FETCHING_RSVP_LIST';
export const FETCH_RSVP_LIST_SUCCESS = 'FETCH_RSVP_LIST_SUCCESS';
export const CANCEL_RSVP_SUCCESS = 'CANCEL_RSVP_SUCCESS';

export const ON_FETCHING_MY_EVENTS = 'ON_FETCHING_MY_EVENTS';
export const FETCH_MY_EVENTS_SUCCESS = 'FETCH_MY_EVENTS_SUCCESS';
export const UPDATE_MY_EVENT_SUCCESS = 'UPDATE_MY_EVENT_SUCCESS';
export const DELETE_MY_EVENT_SUCCESS = 'DELETE_MY_EVENT_SUCCESS';

// THIS IS FOR HOME PAGE

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const ON_GET_EVENTS = 'ON_GET_EVENTS';
export const ON_RSVP = 'ON_RSVP';
export const RSVP_EVENT_SUCCESS = 'RSVP_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';

export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const ON_GET_BLOGS = 'ON_GET_BLOGS';
export const ON_POSTING_BLOG_COMMENT = 'ON_POSTING_BLOG_COMMENT';
export const COMMENT_BLOG_SUCCESS = 'COMMENT_BLOG_SUCCESS';

export const ON_FILTER = 'ON_FILTER';
export const FILTER_EVENTS_SUCCESS = 'FILTER_EVENTS_SUCCESS';

export const SEARCH_BLOGS_AND_EVENTS_SUCCESS =
	'SEARCH_BLOGS_AND_EVENTS_SUCCESS';
