export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LAUNCH_FIRST_CLICKED = 'LAUNCH_FIRST_CLICKED';
