export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

// THIS IS FOR PROFILE PAGE
export const GET_MY_BLOGS_SUCCESS = 'GET_MY_BLOGS_SUCCESS';
export const DELETE_MY_BLOG_SUCCESS = 'DELETE_MY_BLOG_SUCCESS';

export const GET_RSVP_LIST_SUCCESS = 'GET_RSVP_LIST_SUCCESS';
export const CANCEL_RSVP_SUCCESS = 'CANCEL_RSVP_SUCCESS';

export const GET_MY_EVENTS_SUCCESS = 'GET_MY_EVENTS_SUCCESS';
export const UPDATE_MY_EVENT_SUCCESS = 'UPDATE_MY_EVENT_SUCCESS';
export const DELETE_MY_EVENT_SUCCESS = 'DELETE_MY_EVENT_SUCCESS';

// THIS IS FOR HOME PAGE

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const ON_GET_EVENTS = 'ON_GET_EVENTS';
export const RSVP_EVENT_SUCCESS = 'RSVP_EVENT_SUCCESS';

export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const ON_GET_BLOGS = 'ON_GET_BLOGS';
export const ON_POSTING_BLOG_COMMENT = 'ON_POSTING_BLOG_COMMENT';
export const COMMENT_BLOG_SUCCESS = 'COMMENT_BLOG_SUCCESS';

export const ON_FILTER = 'ON_FILTER';
export const FILTER_EVENTS_SUCCESS = 'FILTER_EVENTS_SUCCESS';

export const SEARCH_BLOGS_AND_EVENTS_SUCCESS =
	'SEARCH_BLOGS_AND_EVENTS_SUCCESS';
